#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
#ifndef RIVERUNTIME_SWIFT_H
#define RIVERUNTIME_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import QuartzCore;
@import UIKit;
#endif

#import <RiveRuntime/RiveRuntime.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RiveRuntime",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSCoder;

SWIFT_CLASS("_TtC11RiveRuntime14FPSCounterView")
@interface FPSCounterView : UILabel
- (nonnull instancetype)init;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class RiveStateMachineInstance;
@class RiveLinearAnimationInstance;
@class RiveArtboard;
@class RiveFile;
@class NSString;
@class NSBundle;
@protocol RiveFileDelegate;

SWIFT_CLASS("_TtC11RiveRuntime9RiveModel")
@interface RiveModel : NSObject
@property (nonatomic, strong) RiveStateMachineInstance * _Nullable stateMachine;
@property (nonatomic, strong) RiveLinearAnimationInstance * _Nullable animation;
@property (nonatomic, readonly, strong) RiveArtboard * _Null_unspecified artboard;
- (nonnull instancetype)initWithRiveFile:(RiveFile * _Nonnull)riveFile OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithFileName:(NSString * _Nonnull)fileName extension:(NSString * _Nonnull)extension in:(NSBundle * _Nonnull)bundle loadCdn:(BOOL)loadCdn error:(NSError * _Nullable * _Nullable)error customLoader:(LoadAsset _Nullable)customLoader OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithWebURL:(NSString * _Nonnull)webURL delegate:(id <RiveFileDelegate> _Nonnull)delegate loadCdn:(BOOL)loadCdn OBJC_DESIGNATED_INITIALIZER;
/// Sets a new Artboard and makes the current StateMachine and Animation nil
- (BOOL)setArtboard:(NSString * _Nonnull)name error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setStateMachine:(NSString * _Nonnull)name error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setAnimation:(NSString * _Nonnull)name error:(NSError * _Nullable * _Nullable)error;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP11RiveRuntime18RivePlayerDelegate_")
@protocol RivePlayerDelegate
- (void)playerWithPlayedWithModel:(RiveModel * _Nullable)riveModel;
- (void)playerWithPausedWithModel:(RiveModel * _Nullable)riveModel;
- (void)playerWithLoopedWithModel:(RiveModel * _Nullable)riveModel type:(NSInteger)type;
- (void)playerWithStoppedWithModel:(RiveModel * _Nullable)riveModel;
- (void)playerWithDidAdvanceby:(double)seconds riveModel:(RiveModel * _Nullable)riveModel;
@end

@class StateMachineInput;
@class RiveEvent;

SWIFT_PROTOCOL("_TtP11RiveRuntime24RiveStateMachineDelegate_")
@protocol RiveStateMachineDelegate
@optional
- (void)touchBeganOnArtboard:(RiveArtboard * _Nullable)artboard atLocation:(CGPoint)location;
- (void)touchMovedOnArtboard:(RiveArtboard * _Nullable)artboard atLocation:(CGPoint)location;
- (void)touchEndedOnArtboard:(RiveArtboard * _Nullable)artboard atLocation:(CGPoint)location;
- (void)touchCancelledOnArtboard:(RiveArtboard * _Nullable)artboard atLocation:(CGPoint)location;
- (void)stateMachine:(RiveStateMachineInstance * _Nonnull)stateMachine receivedInput:(StateMachineInput * _Nonnull)input;
- (void)stateMachine:(RiveStateMachineInstance * _Nonnull)stateMachine didChangeState:(NSString * _Nonnull)stateName;
- (void)onRiveEventReceivedOnRiveEvent:(RiveEvent * _Nonnull)riveEvent;
@end


@class UITouch;
@class UIEvent;
@protocol MTLDevice;

SWIFT_CLASS("_TtC11RiveRuntime8RiveView")
@interface RiveView : RiveRendererView
@property (nonatomic, weak) id <RivePlayerDelegate> _Nullable playerDelegate;
@property (nonatomic, weak) id <RiveStateMachineDelegate> _Nullable stateMachineDelegate;
/// Shows or hides the FPS counter on this RiveView
@property (nonatomic) BOOL showFPS;
/// Shows or hides the FPS counters on all RiveViews
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL showFPSCounters;)
+ (BOOL)showFPSCounters SWIFT_WARN_UNUSED_RESULT;
+ (void)setShowFPSCounters:(BOOL)value;
/// Minimalist constructor, call <code>.configure</code> to customize the <code>RiveView</code> later.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithModel:(RiveModel * _Nonnull)model autoPlay:(BOOL)autoPlay;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// This resets the view with the new model. Useful when the <code>RiveView</code> was initialized without one.
- (BOOL)setModel:(RiveModel * _Nonnull)model autoPlay:(BOOL)autoPlay error:(NSError * _Nullable * _Nullable)error;
/// Hints to underlying CADisplayLink the preferred FPS to run at
/// \param preferredFramesPerSecond Integer number of seconds to set preferred FPS at
///
- (void)setPreferredFramesPerSecondWithPreferredFramesPerSecond:(NSInteger)preferredFramesPerSecond;
/// Hints to underlying CADisplayLink the preferred frame rate range
/// \param preferredFrameRateRange Frame rate range to set
///
- (void)setPreferredFrameRateRangeWithPreferredFrameRateRange:(CAFrameRateRange)preferredFrameRateRange SWIFT_AVAILABILITY(ios,introduced=15.0);
/// Advances the Artboard and either a StateMachine or an Animation.
/// Also fires any remaining events in the queue.
/// \param delta elapsed seconds since the last advance
///
- (void)advanceWithDelta:(double)delta;
/// This is called in the middle of drawRect. Override this method to implement
/// custom draw logic
- (void)drawRive:(CGRect)rect size:(CGSize)size;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesMoved:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesCancelled:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (null_unspecified instancetype)initWithFrame:(CGRect)frameRect SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frameRect device:(id <MTLDevice> _Nullable)device SWIFT_UNAVAILABLE;
@end


/// An object used for controlling a RiveView. For most common Rive files you should only need
/// to interact with a <code>RiveViewModel</code> object.
/// <ul>
///   <li>
///     Usage:
///     <ul>
///       <li>
///         You should initialize with either an Animation name or a StateMachine name, but not both.
///         Only one will be used and if both are given the StateMachine will be used.
///       </li>
///       <li>
///         Default StateMachine or Animation from the file can be used by leaving their parameters nil
///       </li>
///     </ul>
///   </li>
///   <li>
///     Examples:
///   </li>
/// </ul>
/// \code
/// // SwiftUI Example
/// struct Animation: View {
///     var body: some View {
///         RiveViewModel(fileName: "cool_rive_file").view()
///     }
/// }
///
/// \endcode\code
/// // UIKit Example
/// class AnimationViewController: UIViewController {
///    @IBOutlet weak var riveView: RiveView!
///    var viewModel = RiveViewModel(fileName: "cool_rive_file")
///
///    override func viewDidLoad() {
///       viewModel.setView(riveView)
///    }
/// }
///
/// \endcode
SWIFT_CLASS("_TtC11RiveRuntime13RiveViewModel")
@interface RiveViewModel : NSObject <RiveFileDelegate, RivePlayerDelegate, RiveStateMachineDelegate>
@property (nonatomic, readonly, strong) RiveView * _Nullable riveView;
- (nonnull instancetype)init:(RiveModel * _Nonnull)model stateMachineName:(NSString * _Nullable)stateMachineName fit:(RiveFit)fit alignment:(RiveAlignment)alignment autoPlay:(BOOL)autoPlay artboardName:(NSString * _Nullable)artboardName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(RiveModel * _Nonnull)model animationName:(NSString * _Nullable)animationName fit:(RiveFit)fit alignment:(RiveAlignment)alignment autoPlay:(BOOL)autoPlay artboardName:(NSString * _Nullable)artboardName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFileName:(NSString * _Nonnull)fileName extension:(NSString * _Nonnull)extension in:(NSBundle * _Nonnull)bundle stateMachineName:(NSString * _Nullable)stateMachineName fit:(RiveFit)fit alignment:(RiveAlignment)alignment autoPlay:(BOOL)autoPlay artboardName:(NSString * _Nullable)artboardName loadCdn:(BOOL)loadCdn customLoader:(LoadAsset _Nullable)customLoader OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithWebURL:(NSString * _Nonnull)webURL stateMachineName:(NSString * _Nullable)stateMachineName fit:(RiveFit)fit alignment:(RiveAlignment)alignment autoPlay:(BOOL)autoPlay loadCdn:(BOOL)loadCdn artboardName:(NSString * _Nullable)artboardName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithWebURL:(NSString * _Nonnull)webURL animationName:(NSString * _Nullable)animationName fit:(RiveFit)fit alignment:(RiveAlignment)alignment autoPlay:(BOOL)autoPlay loadCdn:(BOOL)loadCdn artboardName:(NSString * _Nullable)artboardName OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, strong) RiveModel * _Nullable riveModel;
@property (nonatomic, readonly) BOOL isPlaying;
@property (nonatomic) BOOL autoPlay;
@property (nonatomic) RiveFit fit;
@property (nonatomic) RiveAlignment alignment;
/// Hints to underlying CADisplayLink in RiveView (if created) the preferred FPS to run at
/// For more, see: https://developer.apple.com/documentation/quartzcore/cadisplaylink/1648421-preferredframespersecond
/// \param preferredFramesPerSecond Integer number of seconds to set preferred FPS at
///
- (void)setPreferredFramesPerSecondWithPreferredFramesPerSecond:(NSInteger)preferredFramesPerSecond;
/// Hints to underlying CADisplayLink in RiveView (if created) the preferred frame rate range
/// For more, see: https://developer.apple.com/documentation/quartzcore/cadisplaylink/3875343-preferredframeraterange
/// \param preferredFrameRateRange Frame rate range to set
///
- (void)setPreferredFrameRateRangeWithPreferredFrameRateRange:(CAFrameRateRange)preferredFrameRateRange SWIFT_AVAILABILITY(ios,introduced=15.0);
/// Starts the active Animation or StateMachine from it’s last position. It will start
/// from the beginning if the active Animation has ended or a new one is provided.
/// \param animationName The name of a new Animation to play on the current Artboard
///
/// \param loop The loop mode for the active Animation
///
- (void)playWithAnimationName:(NSString * _Nullable)animationName loop:(RiveLoop)loop direction:(RiveDirection)direction;
/// Halts the active Animation or StateMachine and will resume from it’s current position when next played
- (void)pause;
/// Halts the active Animation or StateMachine and sets it at its starting position
- (void)stop;
/// Sets the active Animation or StateMachine back to their starting position
- (void)reset;
/// Instantiates elements in the model needed to play in a <code>RiveView</code>
- (BOOL)configureModelWithArtboardName:(NSString * _Nullable)artboardName stateMachineName:(NSString * _Nullable)stateMachineName animationName:(NSString * _Nullable)animationName error:(NSError * _Nullable * _Nullable)error;
/// Sets the Artboard, StateMachine or Animation back to the first one given to the RiveViewModel
- (void)resetToDefaultModel;
/// Provide the active StateMachine a <code>Trigger</code> input
/// \param inputName The name of a <code>Trigger</code> input on the active StateMachine
///
- (void)triggerInput:(NSString * _Nonnull)inputName;
/// Provide the active StateMachine a <code>Boolean</code> input
/// \param inputName The name of a <code>Boolean</code> input on the active StateMachine
///
/// \param value A Bool value for the input
///
- (void)setBoolInput:(NSString * _Nonnull)inputName value:(BOOL)value;
/// Provide the active StateMachine a <code>Number</code> input
/// \param inputName The name of a <code>Number</code> input on the active StateMachine
///
/// \param value A Float value for the input
///
- (void)setInput:(NSString * _Nonnull)inputName value:(float)value;
/// Provide the active StateMachine a <code>Number</code> input
/// \param inputName The name of a <code>Number</code> input on the active StateMachine
///
/// \param value A Double value for the input
///
- (void)setNumberInput:(NSString * _Nonnull)inputName value:(double)value;
/// Get a text value from a specified text run
/// \param textRunName The name of a <code>Text Run</code> on the active Artboard
///
///
/// returns:
/// String text value of the specified text run if applicable
- (NSString * _Nullable)getTextRunValue:(NSString * _Nonnull)textRunName SWIFT_WARN_UNUSED_RESULT;
/// Set a text value for a specified text run
/// \param textRunName The name of a <code>Text Run</code> on the active Artboard
///
/// \param value A String value for the text run
///
- (BOOL)setTextRunValue:(NSString * _Nonnull)textRunName textValue:(NSString * _Nonnull)textValue error:(NSError * _Nullable * _Nullable)error;
- (NSArray<NSString *> * _Nonnull)artboardNames SWIFT_WARN_UNUSED_RESULT;
/// Makes a new <code>RiveView</code> for the instance property with data from model which will
/// replace any previous <code>RiveView</code>. This is called when first drawing a <code>RiveViewRepresentable</code>.
///
/// returns:
/// Reference to the new view that the <code>RiveViewModel</code> will be maintaining
- (RiveView * _Nonnull)createRiveView SWIFT_WARN_UNUSED_RESULT;
/// Gives updated layout values to the provided <code>RiveView</code>. This is called in
/// the process of re-displaying <code>RiveViewRepresentable</code>.
/// \param view the <code>RiveView</code> that will be updated
///
- (void)updateWithView:(RiveView * _Nonnull)view;
/// Stops maintaining a connection to any <code>RiveView</code>
- (void)deregisterView;
/// This can be used to connect with and configure an <code>RiveView</code> that was created elsewhere.
/// Does not need to be called when updating an already configured <code>RiveView</code>. Useful for
/// attaching views created in a <code>UIViewController</code> or Storyboard.
/// \param view the <code>RiveView</code> that this <code>RiveViewModel</code> will maintain
///
- (void)setView:(RiveView * _Nonnull)view;
/// Called by RiveFile when it finishes downloading an asset asynchronously
- (BOOL)riveFileDidLoad:(RiveFile * _Nonnull)riveFile error:(NSError * _Nullable * _Nullable)error;
- (void)playerWithPlayedWithModel:(RiveModel * _Nullable)riveModel;
- (void)playerWithPausedWithModel:(RiveModel * _Nullable)riveModel;
- (void)playerWithLoopedWithModel:(RiveModel * _Nullable)riveModel type:(NSInteger)type;
- (void)playerWithStoppedWithModel:(RiveModel * _Nullable)riveModel;
- (void)playerWithDidAdvanceby:(double)seconds riveModel:(RiveModel * _Nullable)riveModel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Simple data type for passing state machine input names and their types
SWIFT_CLASS("_TtC11RiveRuntime17StateMachineInput")
@interface StateMachineInput : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// State machine input types
typedef SWIFT_ENUM(NSInteger, StateMachineInputType, open) {
  StateMachineInputTypeTrigger = 0,
  StateMachineInputTypeNumber = 1,
  StateMachineInputTypeBoolean = 2,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
